# Generated by Django 5.2.8 on 2025-12-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_days', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leaves_taken',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_annual_leave',
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(default='ADMIN001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='0700000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Line Manager', 'Line Manager'), ('COO', 'COO'), ('CEO', 'CEO')], default='Staff', max_length=20),
        ),
    ]
