# Generated by Django 5.2.8 on 2025-12-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leaverequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leaves_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_annual_leave',
            field=models.IntegerField(default=21),
        ),
    ]
