# Generated by Django 5.2.8 on 2025-12-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_profile_leaves_taken_profile_total_annual_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
    ]
