# Generated by Django 5.2.8 on 2025-12-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leaverequest_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='custom_leave_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype'),
        ),
    ]
