# Generated by Django 5.2.8 on 2025-12-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leaverequest_custom_leave_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='custom_leave_type',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='other_leave_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='other_leave_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
