# Generated by Django 5.2.8 on 2025-12-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_remove_leaverequest_custom_leave_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='other_leave_type',
        ),
    ]
