# Generated by Django 5.2.8 on 2025-12-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='total_days',
        ),
    ]
