# Generated by Django 5.0.6 on 2024-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_remove_profile_leaves_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], default='A', max_length=1),
        ),
    ]